micronaut:
  server.port: 8881
  application:
    name: micronautWsChat

  netty:
    event-loops:
      default:
        prefer-native-transport: true
#    worker:
#      threads: 100

  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"